[package]
name = "pam-oidc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pam_oidc"
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = "0.2.149"

[build-dependencies]
bindgen = "0.68.1"
